version: '3.8'

services:
  database:
    container_name: database_work_entry
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: work_entry
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '33060:3306'
    volumes:
      - ./infra/database:/var/lib/mysql

  php:
    container_name: php_work_entry
    build:
      context: ./infra/docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/work_entry
    depends_on:
      - database

  nginx:
    container_name: nginx_work_entry
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - .:/var/www/work_entry
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database